config/routes.rb
## Routes structure:
## => http_methods route_name => controller#action, as: route_name (As define the route as a named route. Check: http://guides.rubyonrails.org/routing.html#naming-routes)
## => http_methods order: GET, POST, PUT, DELETE
## => Indentation: One empty line between method changes. One empty line and one commented line before new controller route/resource definition
Rails.application.routes.draw do

    ## Application controller routes
    root to: "application#landing"

    get "search" => "application#search", as: "search"
    get "/404", :to => "application#four_oh_four"
    get "/contacts/:importer/callback" => "application#contacts_callback"
    get "/descubra" => "application#browse_by", type: "discover",  as: "discover"
    get "/hot" => "application#browse_by", type: "popular", as: "popular"

    post "/shortener/:text" => "application#shorten_url", as: "shortener"

    ## Session controller routes
    get "login" => "session#new", as: "login"
    get "logout" => "session#destroy", as: "logout"
    get "auth/facebook/callback" => "session#facebook_auth", as: "facebook_auth"
    get "auth/twitter/callback" => "session#twitter_auth", as: "twitter_auth"
    get "auth/instagram/callback" => "session#instagram_auth", as: "instagram_auth"

    post "authenticate" => "session#create", as: "authenticate"

    ## Users controller routes
    get "password/reset/:password_reset_token" => "users#reset_password", as: "reset_password_edit"
    get "timeline" => "users#timeline", as: "timeline"
    get "facebook_friends" => "users#facebook_friends", as: "facebook_friends"
    get "follow_all_facebook_friends" => "users#follow_all_facebook_friends", as: "follow_all_facebook_friends"

    post "save_profile_photo" => "users#save_profile_photo", as: "save_profile_photo"
    post "save_cover_photo" => "users#save_cover_photo", as: "save_cover_photo"
    post "reset_password" => "users#reset_password_email", as: "reset_password"
    post "follow_or_unfollow/:id" => "users#follow_or_unfollow", constraints: {id: /.*/}, as: "follow_or_unfollow"
    post "follow_all_email_contacts" => "users#follow_all_email_contacts", as: "follow_all_email_contacts"
    post "invite_friend" => "users#invite_single_contact", as: "invite_friend"
    post "invite_all_contacts" => "users#invite_all_email_contacts", as: "invite_all_contacts"
    post "merge_accounts" => "users#merge_accounts", as: "merge_accounts"
    post "complete_registration" => "users#complete_registration", as: "complete_registration"

    put "update_password" => "users#update_password", as: "update_password"
    put "finish_tour" => "users#finish_tour", as: "finish_tour"

    ## Texts controller routes
    get "load_search_results" => "texts#load_search_results", as: "load_search_results"

    post ":id/create_tag_path" => "texts#create_tag", as: "create_tag"

    delete ":id/delete_tag/:tag_id" => "texts#delete_tag", as: "delete_tag"

    ## Categories controller routes
    get "/load_from/:category" => "categories#load_from", as: "load_from"
    get "c/:locale" => "categories#index", as: "category_with_locale"

    ## Tags controller routes
    get "/tags" => "tags#index", as: "tags"
    get "/load_texts" => "tags#load_texts", as: "load_from_tags"

    ## Categories resources
    resources :categories, param: :locale_key, only: [:index], path: "c" do
        get "last/:locale" => "categories#last_texts_full", as: "last_texts_full"
        get "most/:locale" => "categories#most_viewed_full", as: "most_viewed_full"
    end

    ## Texts resources
    resources :texts, only: [:new, :create, :edit, :update, :show, :destroy], path: "t" do
        get "commentline" => "texts#commentline", as: "commentline"
        
        post "publish" => "texts#publish", as: "publish"
        post "post_comment" => "texts#post_comment", as: "post_comment"
        post "recommendations_details" => "texts#recommendations_details", as: "recommendations_details"
        post "cover_text_photo" => "texts#save_text_cover", as: "insert_cover"
        post "insert_text_image" => "texts#save_text_image", as: "insert_image"
        
        delete "delete_comment" => "texts#delete_comment", as: "delete_comment"
        delete "delete_text_image" => "texts#delete_text_image", as: "delete_image"
    end

    ## Users resources
    resources :users, :param => :id, constraints: {id: /.*/}, only: [:new, :create, :edit, :update], path: "u" do
        get "/profile" => "users#profile", as: "show"
        get "/following" => "users#following", as: "following"
        get "/followers" => "users#followers", as: "followers"
        get "/stats" => "users#see_stats", as: "see_stats"
        get "/link_facebook" => "users#link_facebook_account", as: "link_facebook"

        post "/deactivate_account" => "users#deactivate_account", as: "deactivate_account"

        put "/unlink_facebook" => "users#unlink_facebook", as: "unlink_facebook"
        put "/unlink_twitter" => "users#unlink_twitter", as: "unlink_twitter"
        put "/unlink_instagram" => "users#unlink_instagram", as: "unlink_instagram"

        member do
            post "/recommend/:text_id/" => "users#recommend", as: "recommend"
        end
    end

    devise_for :master_scribers
    authenticate :master_scriber do
      mount RailsAdmin::Engine => '/admin'
    end
end

app/controllers/users_controller.rb
## TODO: Review load_* methods. DRY!
## Maybe add them to ApplicationController and use Delegator??
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy, :follow_or_unfollow, :profile, :following, :followers, :deactivate_account, :see_stats, :recommend]
  before_action :check_credentials, only: [:edit, :update, :destroy, :following, :followers, :timeline]
  before_action :check_permission, only: [:edit, :destroy, :see_stats]
  before_action :fill_suggestions, only: [:timeline, :profile]
  before_action :check_activity, only: [:profile]
  before_action :show do
    render_header(true)
    render_footer(true)
  end

  helper_method :link_facebook, :link_twitter, :link_instagram

  ## GET /u
  ## Params: id
  ## Rails generated resource
  def show
  end

  ## GET /u/id/edit
  ## Params: id
  ## Rails generated resource
  def edit
    @country_codes = Country.all.collect { |c| ["#{c[0]} - #{Country[c[1]].country_code}", Country[c[1]].country_code] }
    @phone_code_selected = @user.phone_country_code || Country[@user.country_code].country_code
  end

  ## GET /u/new
  ## Params: 
  ## Rails generated resource
  def new
    #@user = User.new
    redirect_to root_url
  end

  ## POST /reset_password
  ## Params: email
  ## Success: redirect_to login page
  ## Error: TODO
  def reset_password_email
    @user = User.where(email: params[:email]).first
    @user.send_reset_email if @user
    if @user.nil?
      redirect_to reset_password_url, flash: {error: t(:email_doesnt_exist)}
    else
      redirect_to root_url, notice: t(:email_sent)
    end
  end

  ## GET /password/reset/password_reset_token
  ## Params: password_reset_token
  ## Success: renders reset_password view
  ## Error: redirect_to login page with invalid confirmation token message
  def reset_password
    @user = User.where(password_reset_token: params[:password_reset_token]).first
    
    unless @user
      redirect_to root_url, notice: t(:invalid_confirmation_token)
    end
  end

  ## PUT /update_password
  ## Params: password_reset_token, password, password_confirmation
  ## Success: redirect_to login page with reset password success notice
  ## Error: Renders model errors
  def update_password
    @user = User.where(update_password_params).first
    respond_to do |format|
      if @user.update(user_params)
        @user.password_reset_token = nil
        @user.save
        format.html {redirect_to root_url, notice: t(:pass_reset_success)}
      else
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  ## POST /save_profile_photo
  ## Params: profile_photo
  ## Success: Returns profile_photo url
  ## Error: Renders model errors

  ## POST /save_cover_photo
  ## Params: cover_photo
  ## Success: Returns cover_photo url
  ## Error: Renders model errors

  %w(profile_photo cover_photo).each do |att|
    define_method("save_#{att}") do
      @current_user.send("#{att}=", params[:user][att.to_sym])
      respond_to do |format|
        if @current_user.save
          format.json {render json: @current_user.send("#{att}").url, status: :ok}
        else
          format.json {render json: @current_user.errors, status: :unprocessable_entity}
        end
      end
    end
  end

  ## POST /u
  ## Params: email, email_confirmation, password, password_confirmation, first_name, last_name
  ## Success: redirect_to user profile
  ## Error: Renders model errors
  ## TODO: Review error handling
  def create
    @user = User.new(user_params)
    @user.last_login = Time.now

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        SystemMailer.delay({run_at: 10.seconds.from_now}).welcome_email(@user)
        format.json { render json: {url: discover_url}, status: :created, location: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  ## POST /complete_registration
  ## Params: email, password, password_confirmation, twitter_uid
  ## Success: redirect_to user profile
  ## Error: Renders model errors
  ## TODO: Review error handling
  def complete_registration
    @user = User.where(email: params[:email]).first || User.where(:"#{session[:provider]}_uid" => session[:social_uid]).first
    attrs = {
      email: params[:email],
      last_login: Time.now,
      is_active: true
    }

    if @user.send("#{session[:provider]}_uid").nil?
      @social_user = User.where(:"#{session[:provider]}_uid" => session[:social_uid]).first
      user_attrs = @user.attributes.select{ |k,v| k.start_with?(session[:provider])}
      user_attrs.each{|k,v| user_attrs[k] = @social_user.send(k)}

      attrs.merge!(user_attrs)
    end
    @user.update(attrs)

    respond_to do |format|
      session[:provider] = nil
      session[:social_uid] = nil
      session[:user_id] = @user.id
      SystemMailer.delay({run_at: 10.seconds.from_now}).welcome_email(@user)
      redirect_url = (!@user.facebook_uid.nil? && !@user.done_facebook_follow_friends) ? facebook_friends_url : (request.referrer || discover_url )

      format.html { redirect_to redirect_url }
      format.json { render :show, status: :created, location: @user }
    end
  end

  ## PUT /finish_tour
  ## Params: 
  ## Success: Mark tour flag for user as true
  def finish_tour
    @current_user.done_update = true
    @current_user.save!
    respond_to do |format|
      format.json { render json: {success: true}, status: :ok}
    end
  end

  ## PUT /u/id
  ## Params: id
  ## Success: redirect_to user profile
  ## Error: Renders model errors
  ## TODO: Review error handling
  def update
    respond_to do |format|
      
      action = if params[:user].nil?
        @user.preferences.update_attributes(preferences_params)
      else
        @user.update(user_params)
      end

      if action
        format.json { render json: {url: user_show_url(@user)}, status: :ok, location: @user } if request.xhr?
        format.html { redirect_to user_show_url(@user) } unless request.xhr?
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  ## POST /merge_accounts
  ## Params: 
  ## Success: Merge existent facebook account with current user
  def merge_accounts
    @merged_account = User.where('facebook_uid = ? AND id <> ?', @current_user.facebook_uid, @current_user.id).first
    User.merge(@current_user, @merged_account)

    respond_to do |format|
      flash[:notice] = t(:merged_with_success)
      format.json { render json: {success: true, curr: @current_user}, status: :ok }
    end
  end

  ## PUT /u/id/unlink_facebook
  ## Params: id
  ## Success: Unlink all facebook data from user

  ## PUT /u/id/unlink_twitter
  ## Params: id
  ## Success: Unlink all twitter data from user

  ## PUT /u/id/unlink_instagram
  ## Params: id
  ## Success: Unlink all instagram data from user
  %w(twitter facebook instagram).each do |service|
    define_method("unlink_#{service}") do
      attrs = @current_user.attributes.select{ |k,v| k.start_with?(service)}
      attrs.each{|k,v| attrs[k] = nil}
      @current_user.update(attrs)

      respond_to do |format|
        flash[:notice] = t(:removed_with_success)
        format.html { render partial: "users/social/link_#{service}", locals: {linked: false} }
      end
    end
  end

  ## DELETE /u/id
  ## Params: id
  ## Unused method
  ## Rails generated method
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url}
      format.json { head :no_content }
    end
  end

  ## GET /u/id/profile
  ## Params: id (friendly)
  ## Success: redirect_to user profile page
  ## Error: 404
  ## TODO: Error handling
  def profile
    @texts_page = params[:texts_page] || 1
    @texts = @user.texts.order(published_at: :desc).page(@texts_page).per(3).where(is_draft: false)

    @drafts_page = params[:drafts_page] || 1
    @drafts = @user.texts.order(created_at: :desc).page(@drafts_page).per(4).where(is_draft: true)
    
    respond_to do |format|
      format.html {render layout: !request.xhr?, status: :ok}
    end
  end

  ## GET /timeline
  ## Params: 
  ## Success: Renders entire timeline page if normal request, render timeline partial if AJAX request.
  ## TODO: Error handling
  def timeline
    @user = @current_user

    @timeline_page = params[:page].blank? ? 1 : params[:page]
    @tl = @current_user.timeline(@timeline_page)
    
    respond_to do |format|
      format.html {render layout: !request.xhr?, status: :ok}
    end

  end

  ## POST /follow_or_unfollow/id
  ## Params: id
  ## Success:
  ##    {
  ##      refreshed_counter: Followed user refreshed counter
  ##      refresh_who: Section to be updated
  ##      refreshed_action: Followed or unfollowed?
  ##    }
  ## Error: 
  ## TODO: Error handling
  def follow_or_unfollow
    was_following = @current_user.follow?(@user)
    was_following ? @current_user.unfollow(@user) : @current_user.follow(@user)
    respond_to do |format|
      format.json {
        render json: {
          his_refreshed_counter: t(:followers, count: @user.follower_count), 
          my_refreshed_counter: t(:following, count: @current_user.following_count),
          his_refreshed_container: "#follower-count-#{@user.id}", 
          my_refreshed_container: "#following-count-#{@current_user.id}",
          refreshed_current: t(:follow_or_unfollow, count: (!was_following ? 1 : 0)),
          refreshed_hover: t(:follow_or_unfollow, count: (!was_following ? 2 : 0)),
          old_class: !was_following ? 'follow-btn' : 'following-btn',
          refreshed_class: !was_following ? 'following-btn' : 'follow-btn'
        }
      }
    end
  end

  ## GET /u/id/following
  ## Params: id, page
  ## Success: Render list of users the followed by the selected user
  ## Error: 
  ## TODO: Error handling

  ## GET /u/id/followers
  ## Params: id, page

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_direct_upload.html.haml
= s3_uploader_form callback_url: callback, data: {:"upload-error" => t(:upload_error)} ,class: 's3_uploader', callback_param: "user[#{param}]", id: "#{param}", expiration: 24.hours.from_now.utc.iso8601, max_file_size: 50.megabytes do
  = file_field_tag :file, accept: 'image/png,image/gif,image/jpeg'

app/views/users/_existing_account_modal.html.haml
#merge-acc-modal.modal.fade{role: "dialog", aria: {labelledby: "modal-title", hidden: true}}
  .modal-dialog
    .modal-content
      .modal-header.text-center
        = image_tag 'icons/error-icon.svg', id: "error-icon"
        %button.close{type: "button", data: {dismiss: "modal"}}
          %span{aria: {hidden: true}}= "X"
          %span.sr-only= "Close"
        %h2= "Oops"
        %h4= t(:acc_in_use_subtitle)
      .modal-body
        %p= t(:acc_in_use_desc_pt1)
        = render partial: "users/user_list_fol", locals: {users: User.where(id: params[:fb_exists])}
        %p= t(:acc_in_use_desc_pt2)
      .modal-footer
        %button{class: modal_btn_classes, data: {merge_url: merge_accounts_url}}= t(:merge)

app/views/users/_existing_contacts.html.haml
%section#existing-contacts
  .sg-container.user-section
    .section-header.sg-row
      %h3= t(:contacts_using_scribe)
    .sg-row.contacts-list
      = render "users/user_list_fol", users: users
    .sg-row
      = link_to t(:follow_all), '#', data: {action: follow_all_email_contacts_url, emails: users.map{|c| c.email}}, class: 'follow-all-btn', id: 'follow-all-email'
    .sg-row
      %button#skip-step= t(:skip_this_step)

app/views/users/_reference_panel.html.haml
- references.each do |k,v|
  .sg-row
    %span.ref.pull-left= k.capitalize
    %span.count.pull-right= v

app/views/users/_stats_references_views.html.haml
- texts.sort{ |x,y| y.published_at <=> x.published_at }.each do |text|
  %ul.listed-text.sg-row.horizontal-list
    %li.text-date.text-center
      %h2.day= text.published_at.strftime('%d')
      %h4.month= I18n.l(text.published_at, format: :short_month).upcase
      %h4.year= text.published_at.strftime('%Y')
    %li.text-information.sg-col-4
      .sg-row
        %h1.title= text.title
      .sg-row
        %h2.subtitle= text.subtitle
    %li.text-refs.text-center.sg-offset-1.sg-col-2
      = render "reference_panel", references: text.references
    %li.text-access.text-center.sg-offset-1
      = link_to t(:read_text), text

app/views/users/_stats_text_recommendations.html.haml
- texts.sort{ |x,y| y.recommendations_count <=> x.recommendations_count }.each do |text|
  %ul.listed-text.sg-row.horizontal-list
    %li.text-date.text-center
      %h2.day= text.published_at.strftime('%d')
      %h4.month= I18n.l(text.published_at, format: :short_month).upcase
      %h4.year= text.published_at.strftime('%Y')
    %li.text-information.sg-col-4
      .sg-row
        %h1.title= text.title
      .sg-row
        %h2.subtitle= text.subtitle
    %li.text-stat.text-center.sg-offset-1.sg-col-2
      %h1.monster-font
        = link_to text.recommendations_count, (text.recommendations_count > 0 ? text_recommendations_details_url(text) : ''), remote: true, method: :post, class: 'recommendation-details'
    %li.text-access.text-center.sg-offset-1
      = link_to t(:read_text), text
= render "scribe_modal", modal_title: t(:recommendations), modal_subtitle: t(:scribers_who_recommended), modal_btn_classes: "btn btn-scribe full-width-btn btn-scribe-lb"

app/views/users/_stats_text_views.html.haml
- texts.sort{ |x,y| y.impressionist_count(filter: impression_filter) <=> x.impressionist_count(filter: impression_filter)}.each do |text|
  %ul.listed-text.sg-row.horizontal-list
    %li.text-date.text-center
      %h2.day= text.published_at.strftime('%d')
      %h4.month= I18n.l(text.published_at, format: :short_month).upcase
      %h4.year= text.published_at.strftime('%Y')
    %li.text-information.sg-col-4
      .sg-row
        %h1.title= text.title
      .sg-row
        %h2.subtitle= text.subtitle
    %li.text-stat.text-center.sg-offset-1.sg-col-2
      %h1.monster-font= text.impressionist_count(filter: impression_filter)
    %li.text-access.text-center.sg-offset-1
      = link_to t(:read_text), text

app/views/users/_user_header_nav.html.haml
#user-navbar.hidden-xs{role: "navbar"}
  %ul.scribeGrid--newContainer
    -if @current_user
      %li.text-center{class: [('active' if current_page?( timeline_url ))]}
        = link_to t(:timeline), timeline_url, class: 'user-navbar-btn'
      %li.text-center.pull-right{class: [('active' if current_page?( user_show_url(@current_user) ))]}
        = link_to t(:my_profile), user_show_url(@current_user), class: 'user-navbar-btn'
    %li.text-center{class: [('active' if controller.controller_name.eql?("categories"))]}
      = link_to t(:categories), categories_path, class: "user-navbar-btn"
    %li.text-center{class: [('active' if current_page?(discover_url))]}
      = link_to t(:discover), discover_path, class: "user-navbar-btn"
    %li.text-center{class: [('active' if current_page?(popular_path))]}
      = link_to "Popular", popular_path, class: "user-navbar-btn"
    %li.text-center{class: [('active' if current_page?(tags_path))]}
      = link_to "Tags", tags_path, class: "user-navbar-btn"
    - if I18n.locale.eql?(:"pt-BR")
      %li.text-center
        %a{href: "https://shop.wescribe.co", target: "_blank", class: "user-navbar-btn"}= "Scribe Shop"

app/views/users/_user_list.html.haml
- users.each do |user|
  .sg-row
    .user-list-container
      %img.user-thumb.pull-left{src: user.profile_photo.url(:thumbs)}
      .sg-col-5.pull-left
        %h4.name
          = link_to user.name, user_show_url(user)
        %ul.horizontal-list.clearfix
          %li
            = link_to "#{t("activerecord.attributes.user.texts", count: user.texts.where(is_draft: false).size)}", user_show_url(user)
          %li{id: "following-count-#{user.id}"}
            = link_to "#{t(:following, count: user.following_count)}", user_following_url(user)
          %li{id: "follower-count-#{user.id}"}
            = link_to "#{t(:followers, count: user.follower_count)}", user_followers_url(user)
      = follow_unfollow_button(user)

app/views/users/_user_list_fol.html.haml
- users.each.with_index(1) do |user, i|
  .user-grid-container{class: ('last-col' if i%3==0)}
    %ul.fol-options
      %li.user-thumb{style: "background: url(#{user.profile_photo.url(:thumbs)}) center center no-repeat transparent; background-size: cover;"}
      %li.text-date.text-center
        .dates-container
          = fol_container_date(user,user.texts.where(is_draft: false).order("published_at DESC").first)
      %li.fof{class: "#{@current_user.follow?(user) ? 'following-btn' : 'follow-btn'}",data: {toggle: "expand-container"}}
        = follow_unfollow_button(user)
    .fol-info-container
      .fol-info
        %h3.name
          = link_to user.name, user_show_url(user)
        %ul.horizontal-list.clearfix
          %li
            = link_to "#{t("activerecord.attributes.user.texts", count: user.texts.where(is_draft: false).size)}", user_show_url(user)
          %li{id: "following-count-#{user.id}"}
            = link_to "#{t(:following, count: user.following_count)}", user_following_url(user)
          %li{id: "follower-count-#{user.id}"}
            = link_to "#{t(:followers, count: user.follower_count)}", user_followers_url(user)
        %h4.last-text= t(:last_text)
      -if user.texts.where(is_draft: false).order("published_at DESC").first.blank?
        %h4.no-text.text-center= t(:no_texts, user: user.first_name)
      - else
        .text-info{style: ("background: url('#{user.texts.where(is_draft: false).order("published_at DESC").first.cover.photo.url(:half_list)}') center center no-repeat transparent" unless user.texts.where(is_draft: false).order("published_at DESC").first.cover.blank?)}
          .title-and-subtitle
            %h4.title
              = link_to user.texts.where(is_draft: false).order("published_at DESC").first.title, user.texts.where(is_draft: false).order("published_at DESC").first
            %h5.subtitle= user.texts.where(is_draft: false).order("published_at DESC").first.subtitle

app/views/users/facebook_friends.html.haml
= render "users/common/user_header", style: "timeline"
%section#facebook-invite.sg-container.user-section.text-center.facebook-container
  .section-header.sg-row
    %h2= t(:tell_ur_friends)
    %h3= t(:tell_ur_friends_cta)
    %h3.share-text= t(:tell_ur_friends_message_html)
  = link_to t(:tell_ur_friends_cta_btn), "#", data: {href: user_show_url(@current_user)}, class: 'full-width-btn btn-scribe facebook-share'
%div#facebook-friends
  %section#fol-section.sg-container.user-section.facebook-container
    .section-header.sg-row
      .sg-col-10
        %h2= t(:fb_friends_scribe)
        = link_to t(:follow_all), follow_all_facebook_friends_url, class: 'follow-all-btn' unless @scribe_friends.blank?
    %h3.text-center= t(:no_facebook_friends) if @scribe_friends.blank?
    = render "user_list_fol", users: @scribe_friends unless @scribe_friends.blank?

app/views/users/profile.html.haml
= render "users/common/user_header", style: "profile"
%section.scribeGrid--newContainer.profileSection.u-clearfix
  .section--header.scribeGrid--row
    .scribeGrid--newColumn5
      %h2.u-slimTitle= t("#{@user == @current_user ? 'my_last_texts' : 'other_last_texts'}".to_sym, user: @user.name)
    .scribeGrid--newColumn5.u-centralized
      = follow_unfollow_button(@user)
    .scribeGrid--newColumn6.u--mobile-xsHidden
      = form_tag search_url, method: :get, class: 'searchForm' do
        = text_field_tag :query, "#{@query}", placeholder: t(:search), class: 'searchForm--inputField'
  = render "users/suggestions/board", hidden: 'isHidden' if @current_user
  = render "users/profile/published_texts_container", has_texts: !@texts.blank?
-if @current_user && @user == @current_user
  .scribeGrid--row.section-divider
  %section.scribeGrid--newContainer.profileSection.u-clearfix
    .section--header.scribeGrid--row
      .scribeGrid--column10
        %h2.u-slimTitle= t(:my_last_drafts)
    = render "users/profile/drafts_container", has_drafts: !@drafts.blank?

app/views/users/reset_password.html.haml
.container.container-scribe.container-scribe-form
  = form_for @user, url: update_password_url, html: {role: 'form', novalidate: true, method: 'PUT', style: 'padding-top: 75px;'} do |f|
    .form-group{class: ('has-errors' unless @user.errors[:password].empty? && @user.errors[:password_confirmation].empty?)}
      = f.label :password
      = f.password_field :password, class: 'form-control', placeholder: t('activerecord.attributes.user.password'), required: true
      - unless @user.errors[:password].empty?
        - @user.errors[:password].each do |error|
          %p.error-msg= error
      = f.password_field :password_confirmation, class: 'form-control', placeholder: t(:confirm_password), required: true
      - unless @user.errors[:password_confirmation].empty?
        - @user.errors[:password_confirmation].each do |error|
          %p.error-msg= error
      = f.hidden_field :password_reset_token, value: params[:password_reset_token]
      .form-group
        = f.submit t(:submit), class: 'btn btn-scribe btn-scribe-lb full-width-btn'

app/views/users/timeline.html.haml
= render "users/common/user_header", style: "timeline"
%section.scribeGrid--newContainer.timelineSection
  = render "users/suggestions/board", hidden: ''
  .section--header.scribeGrid--row
    .scribeGrid--newColumn9
      %h2.u-slimTitle= t(:timeline)
    .scribeGrid--newColumn7.u--mobile-xsHidden
      = form_tag search_url, method: :get, class: 'searchForm' do
        = text_field_tag :query, "#{@query}", placeholder: t(:search), class: 'searchForm--inputField'
  -if @tl.blank?
    %h3.u-lightFont.u-centralized= t(:empty_timeline)
  = render "application/text/blocks", texts: @tl, container_class: "timelineSection--textBlocks"
  = paginate @tl, params: {controller: "users", action: "timeline"} unless @tl.blank?