config/routes.rb
## Routes structure:
## => http_methods route_name => controller#action, as: route_name (As define the route as a named route. Check: http://guides.rubyonrails.org/routing.html#naming-routes)
## => http_methods order: GET, POST, PUT, DELETE
## => Indentation: One empty line between method changes. One empty line and one commented line before new controller route/resource definition
Rails.application.routes.draw do

    ## Application controller routes
    root to: "application#landing"

    get "search" => "application#search", as: "search"
    get "/404", :to => "application#four_oh_four"
    get "/contacts/:importer/callback" => "application#contacts_callback"
    get "/descubra" => "application#browse_by", type: "discover",  as: "discover"
    get "/hot" => "application#browse_by", type: "popular", as: "popular"

    post "/shortener/:text" => "application#shorten_url", as: "shortener"

    ## Session controller routes
    get "login" => "session#new", as: "login"
    get "logout" => "session#destroy", as: "logout"
    get "auth/facebook/callback" => "session#facebook_auth", as: "facebook_auth"
    get "auth/twitter/callback" => "session#twitter_auth", as: "twitter_auth"
    get "auth/instagram/callback" => "session#instagram_auth", as: "instagram_auth"

    post "authenticate" => "session#create", as: "authenticate"

    ## Users controller routes
    get "password/reset/:password_reset_token" => "users#reset_password", as: "reset_password_edit"
    get "timeline" => "users#timeline", as: "timeline"
    get "facebook_friends" => "users#facebook_friends", as: "facebook_friends"
    get "follow_all_facebook_friends" => "users#follow_all_facebook_friends", as: "follow_all_facebook_friends"

    post "save_profile_photo" => "users#save_profile_photo", as: "save_profile_photo"
    post "save_cover_photo" => "users#save_cover_photo", as: "save_cover_photo"
    post "reset_password" => "users#reset_password_email", as: "reset_password"
    post "follow_or_unfollow/:id" => "users#follow_or_unfollow", constraints: {id: /.*/}, as: "follow_or_unfollow"
    post "follow_all_email_contacts" => "users#follow_all_email_contacts", as: "follow_all_email_contacts"
    post "invite_friend" => "users#invite_single_contact", as: "invite_friend"
    post "invite_all_contacts" => "users#invite_all_email_contacts", as: "invite_all_contacts"
    post "merge_accounts" => "users#merge_accounts", as: "merge_accounts"
    post "complete_registration" => "users#complete_registration", as: "complete_registration"

    put "update_password" => "users#update_password", as: "update_password"
    put "finish_tour" => "users#finish_tour", as: "finish_tour"

    ## Texts controller routes
    get "load_search_results" => "texts#load_search_results", as: "load_search_results"

    post ":id/create_tag_path" => "texts#create_tag", as: "create_tag"

    delete ":id/delete_tag/:tag_id" => "texts#delete_tag", as: "delete_tag"

    ## Categories controller routes
    get "/load_from/:category" => "categories#load_from", as: "load_from"
    get "c/:locale" => "categories#index", as: "category_with_locale"

    ## Tags controller routes
    get "/tags" => "tags#index", as: "tags"
    get "/load_texts" => "tags#load_texts", as: "load_from_tags"

    ## Categories resources
    resources :categories, param: :locale_key, only: [:index], path: "c" do
        get "last/:locale" => "categories#last_texts_full", as: "last_texts_full"
        get "most/:locale" => "categories#most_viewed_full", as: "most_viewed_full"
    end

    ## Texts resources
    resources :texts, only: [:new, :create, :edit, :update, :show, :destroy], path: "t" do
        get "commentline" => "texts#commentline", as: "commentline"
        
        post "publish" => "texts#publish", as: "publish"
        post "post_comment" => "texts#post_comment", as: "post_comment"
        post "recommendations_details" => "texts#recommendations_details", as: "recommendations_details"
        post "cover_text_photo" => "texts#save_text_cover", as: "insert_cover"
        post "insert_text_image" => "texts#save_text_image", as: "insert_image"
        
        delete "delete_comment" => "texts#delete_comment", as: "delete_comment"
        delete "delete_text_image" => "texts#delete_text_image", as: "delete_image"
    end

    ## Users resources
    resources :users, :param => :id, constraints: {id: /.*/}, only: [:new, :create, :edit, :update], path: "u" do
        get "/profile" => "users#profile", as: "show"
        get "/following" => "users#following", as: "following"
        get "/followers" => "users#followers", as: "followers"
        get "/stats" => "users#see_stats", as: "see_stats"
        get "/link_facebook" => "users#link_facebook_account", as: "link_facebook"

        post "/deactivate_account" => "users#deactivate_account", as: "deactivate_account"

        put "/unlink_facebook" => "users#unlink_facebook", as: "unlink_facebook"
        put "/unlink_twitter" => "users#unlink_twitter", as: "unlink_twitter"
        put "/unlink_instagram" => "users#unlink_instagram", as: "unlink_instagram"

        member do
            post "/recommend/:text_id/" => "users#recommend", as: "recommend"
        end
    end

    devise_for :master_scribers
    authenticate :master_scriber do
      mount RailsAdmin::Engine => '/admin'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :container_classes, :facebook_meta, :default_meta, :twitter_meta,
                :fol_container_date,
                :follow_unfollow_button, :generate_locale_url, :text_date,
                :text_block_classes, :mobile_request?

  before_filter :set_locale, :prepare_user
  
  before_action do
    render_footer(true)
    render_header(true)
  end

  def four_oh_four
    @text_suggestions = Text.generate_suggestions(2)
  end

  ## GET /search/query
  ## Params: query page per
  ## Success: Render JSON search results
  def search
    @query = params[:query]
    @user = @current_user || User.new

    @search_params = params[:query].blank? ? nil : params[:query]

    %w(texts_page users_page).each do |param|
      instance_variable_set("@#{param}", (params[param.to_sym].blank? || params[param.to_sym].to_i == 0) ? 1 : params[param.to_sym].to_i)
    end

    @user_results = User.search_for({
      fields: ['bio', 'first_name^2', 'last_name^1.5'],
      filter: {bool: {must: {term: {is_active: true}}}}
      },@search_params)
      .page(@users_page)
      .per(10)
      .records

    @text_results = Text.search_for({
      fields: ['title^3', 'subtitle^2', 'tags.name^3', 'description'],
      filter: {bool: {must: {term: {is_draft: false}}}}
      },@search_params)
      .page(@texts_page)
      .per(10)
      .records

    respond_to do |format|
      format.html
    end
  end

  def browse_by
    @type = params[:type]
    @user = @current_user || User.new

    if @type.eql?("discover")
      @texts = Text.generate_suggestions(150)
        .page(params[:page].blank? ? 1 : params[:page].to_i)
        .per(10)
    elsif @type.eql?("popular")
      @texts = Text.where(language: Language.where(locale: I18n.locale).first)
        .order("recommendations_count DESC")
        .page(params[:page].blank? ? 1 : params[:page].to_i)
        .per(10)
        .uniq
    end

    respond_to do |format|
      format.html
    end
  end

  def landing
    redirect_to timeline_url if @current_user
    unless @current_user
      @user = User.new
      @categories = Category.all
      @highlight = Text.where({is_draft: false, language: Language.where(locale: I18n.locale).first})
        .order("recommendations_count DESC")
        .limit(10)
        .to_a
        .sample

      respond_to do |format|
        format.html
      end
    end
  end

  ## POST /shortener/text
  ## Params: text
  ## Shorten text URL for twitter sharing
  ## Success: Returns shortened URL JSON formatted
  def shorten_url
    text = Text.find(params[:text])
    respond_to do |format|
      format.json {render json: {url: Bitly.client.shorten(url_for(text)).short_url}, status: :ok}
    end
  end

  ## POST contacts/:provider/callback
  ## Params: provider
  ## Fetches user contacts list from one of the following providers: Hotmail, Gmail or Yahoo!
  ## Success: List existing scruibe users from contacts and contacts to invite
  def contacts_callback
    @user = @current_user
    @contacts = request.env['omnicontacts.contacts']
    @on_scribe = User.friends_by_email(@contacts).to_a

    unless @on_scribe.blank?
      @contacts.reject! {
        |h|
        @on_scribe.map{ |u| u.email }.include? h[:email]
      }

      @on_scribe.reject! {
        |u|
        @user.follow?(u) || (u if u.id.eql?(@current_user.id))
      }
    end

    respond_to do |format|
      format.html
    end
  end

  private

  def current_user
    @current_user ||= login_from_session || login_from_cookie
  end

  def login_from_session
    User.find(session[:user_id]) unless session[:user_id].blank?
  end

  def login_from_cookie
    unless cookies['_rm_i'].blank?
      user = User.find(cookies['_rm_i'])
      if cookies['_rm_k'] == Digest::SHA1.hexdigest(user.created_at.to_s)[6,10]
        user.update({
          last_login: Time.now,
          prefered_language: I18n.locale
        })
        user
      else
        nil
      end
    end
  end

  ## Auth helpers

  def check_credentials
    if (@current_user.nil?)
      respond_to do |format|
        format.html {redirect_to root_url, notice: t(:need_login)}
      end
    end
  end

  ## Locale helpers

  def set_locale
    I18n.locale = extract_locale_from_subdomain || I18n.default_locale
    @current_user.update({prefered_language: I18n.locale}) if @current_user
  end

  def prepare_user
    @user ||= User.new
  end


  def extract_locale_from_subdomain
    parsed_locale = request.subdomains.first
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end

  ## Meta tags helpers

  def facebook_meta
    {
      og: {
        type: "website",
        title: "Scribe",
        site_name: "Scribe",
        url: url_for(root_url),
        description: t(:social_description),
        image: [view_context.image_url('covers/facebook/facebook-cover.jpg')]
      }
    }
  end

  def default_meta
    {
      title: "Scribe",
      description: t(:social_description)
    }
  end

  def twitter_meta
    {
      twitter: {
        card: "summary",
        site: "@wescribeapp",
        title: "Scribe",
        description: t(:social_description),
        url: url_for(root_url),
        image: {
          src: view_context.image_url('covers/facebook/facebook-cover.jpg')
        }
      }
    }
  end

  ## Blocks render helpers

  def render_footer(bool)
    @render_footer = bool
  end

  def render_header(bool)
    @render_header = bool
  end

  ## HTML Classes helpers

  def text_block_classes(has_gutter, index, size)
    classes = ["is#{size.capitalize}Sized"]
    if has_gutter && size.eql?("half")
      classes << (index % 2 == 0 ? "scribeGrid--gutterRight1 scribeGrid--mobile-noGutterRight" : "scribeGrid--gutterLeft1 scribeGrid--mobile-noGutterLeft" )
    end
    classes
  end

  def container_classes
    classes = ''
    if !@text.nil? && request.fullpath.include?(edit_text_path(@text))
      classes  << 'is-editor reader-page'
    end
    if (params[:controller].eql?("texts") && params[:action].eql?("show"))
      classes << 'reader-page'
    end
    classes
  end

  def fol_container_date(user,text)
    time_used = text.blank? ? Time.now : text.published_at
    day = Haml::Engine.new("%h2.day #{time_used.strftime('%d')}").render
    month = Haml::Engine.new("%h5.month #{I18n.l(time_used, format: :short_month).upcase}").render
    year = Haml::Engine.new("%h5.year #{time_used.strftime('%Y')}").render

    day + month + year
  end

  def follow_unfollow_button(user)
    if @current_user.blank?
      view_context.link_to(
        t(:follow_or_unfollow, count: 0),
        '#',
        class: 'socialBtn socialBtn--followBtn followIcons sup-trigger'
      )
    else
      is_following = @current_user.follow?(user)
      current_state = t(:follow_or_unfollow, count: (is_following ? 1 : 0))
      hover_state = t(:follow_or_unfollow, count: (is_following ? 2 : 0))
      fob_class = is_following ? 'isFollowing' : ''
      view_context.link_to(
        current_state,
        follow_or_unfollow_url(user), 
        method: :post, 
        remote: true, 
        class: "socialBtn socialBtn--followBtn followIcons js-followUnfollow #{fob_class}",
      ) unless user == @current_user
    end
  end

  def generate_locale_url(locale)
    case locale
    when "en"
      "#{Rails.application.config.en_locale_url}#{request.env['REQUEST_URI']}"
    when "es"
      "#{Rails.application.config.es_locale_url}#{request.env['REQUEST_URI']}"
    else
      "#{Rails.application.config.default_locale_url}#{request.env['REQUEST_URI']}"
    end
  end

  def text_date(text, format)
    date = text.published_at.blank? ? text.updated_at : text.published_at

    if format.eql?(:short_month)
      return I18n.l(date, format: format)
    end

    date.strftime(format)
  end

  def mobile_request?

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/modal/_complete_registration_modal.html.haml
.scribeModal.completeRegistration.modal.fade{role: "dialog", aria: {labelledby: "modal-title", hidden: true}}
  .scribeModal--dialog
    .scribeModal--content.lightColored
      .u-centralized.scribeModal--header
        = image_tag 'missing_photo.svg', class: 'scribeModal--header-topIcon'
        %button.scribeModal--close.darkColored{type: "button", data: {dismiss: "modal"}}
          %span{aria: {hidden: true}}= "X"
          %span.sr-only= "Close"
        %h2.u-lightFont= "Hey #{user.name}"
        %h4.u-lightFont= t(:finish_signup)
      .scribeModal--body.loginModal--body
        = form_tag complete_registration_url, {class: 'scribeForm completeRegistrationForm js-validateForm', method: :post} do
          = text_field_tag :email, user.email, class: 'scribeForm--input', placeholder: t('activerecord.attributes.user.email')
          = submit_tag t(:signup_btn), class: 'button darkBlueColored scribeForm--submit'
- unless session[:provider].nil?
  :javascript
    $('.completeRegistration').modal({
      backdrop: 'static'
    });

app/views/application/modal/_login_modal.html.haml
.scribeModal.loginModal.modal.fade{role: "dialog", aria: {labelledby: "modal-title", hidden: true}}
  .scribeModal--dialog
    .scribeModal--content.lightColored
      .u-centralized.scribeModal--header
        = image_tag 'missing_photo.svg', class: 'scribeModal--header-topIcon'
        %button.scribeModal--close.darkColored{type: "button", data: {dismiss: "modal"}}
          %span{aria: {hidden: true}}= "X"
          %span.sr-only= "Close"
        %h2= t(:do_login)
        %h4.u-slimTitle= t(:or_signup)
      .scribeModal--body.loginModal--body
        = form_tag authenticate_url, {class: 'scribeForm loginForm scribeGrid--newColumn10 js-lowercase-values js-validateForm', remote: true} do
          %h4.u-centralized.u-slimTitle.scribeGrid--row= "Email"
          = text_field_tag :email, params[:email], class: 'scribeForm--input', placeholder: t('activerecord.attributes.user.email'), autocomplete: "off", tabindex: 1
          = password_field_tag :password, nil , class: 'scribeForm--input', placeholder: t('activerecord.attributes.user.password'), autocomplete: "off", tabindex: 2
          .scribeGrid--row.scribeForm--formDetails
            %label.u-pullLeft
              = check_box_tag "persist_session", false, false, class: 'u-pullLeft scribeForm--checkbox', tabindex: 3
              = t(:persist_session)
            = link_to t(:reset_pass), '#', class: 'u-pullRight js-toggleModal', data: {modal: '.scribeModal.resetPassModal'}, tabindex: 4
          = submit_tag "Login", class: 'button mediumLightBlue u-heavyFont u-blockCenter'
          %hr/
          .socialBtn.socialBtn--facebook.readerIcons.scribeGrid--newColumn5.u-blockCenter
            = link_to "Facebook login", '/auth/facebook'
          .socialBtn.socialBtn--twitter.readerIcons.scribeGrid--newColumn5.u-blockCenter
            = link_to "Twitter login", '/auth/twitter'

app/views/application/modal/_registration_modal.html.haml
.scribeModal.signupModal.modal.fade{role: "dialog", aria: {labelledby: "modal-title", hidden: true}}
  .scribeModal--dialog
    .scribeModal--content.lightColored
      .u-centralized.scribeModal--header
        = image_tag 'missing_photo.svg', class: 'scribeModal--header-topIcon'
        %button.scribeModal--close.darkColored{type: "button", data: {dismiss: "modal"}}
          %span{aria: {hidden: true}}= "X"
          %span.sr-only= "Close"
        %h2= t(:signup)
        %h4.u-slimTitle= t(:join_scribe)
      .scribeModal--body.loginModal--body
        = form_for @user, html: {role: 'form', novalidate: true, method: 'post', class: 'scribeForm signupForm js-validateForm', remote: true} do |f|
          .u-clearfix
            = f.label :first_name, class: 'scribeForm--required'
            = f.text_field :first_name, class: 'scribeForm--input', placeholder: t('activerecord.attributes.user.first_name'), required: true
          .u-clearfix
            = f.label :last_name, class: 'scribeForm--required'
            = f.text_field :last_name, class: 'scribeForm--input', placeholder: t('activerecord.attributes.user.last_name'), required: true
          .u-clearfix
            = f.label :email, class: 'scribeForm--required'
            = f.email_field :email, value: @user.email ,class: 'scribeForm--input', placeholder: t('activerecord.attributes.user.email'), required: true
            = f.email_field :email_confirmation, value: @user.email ,class: 'scribeForm--input js-matchPrevious', placeholder: t('activerecord.attributes.user.email_confirmation'), required: true
          .u-clearfix
            = f.label :password, class: 'scribeForm--required'
            = f.password_field :password, class: 'scribeForm--input', placeholder: t('activerecord.attributes.user.password'), required: true
            = f.password_field :password_confirmation, class: 'scribeForm--input js-matchPrevious', placeholder: t(:confirm_password), required: true
          .u-clearfix
            = f.submit t(:signup_btn), class: 'button darkBlueColored scribeForm--submit'
            %small.scribeForm--small= t(:registration_agreement_html)

app/views/application/modal/_reset_password.html.haml
.scribeModal.resetPassModal.modal.fade{role: "dialog", aria: {labelledby: "modal-title", hidden: true}}
  .scribeModal--dialog
    .scribeModal--content.lightColored
      .u-centralized.scribeModal--header
        = image_tag 'missing_photo.svg', class: 'scribeModal--header-topIcon'
        %button.scribeModal--close.darkColored{type: "button", data: {dismiss: "modal"}}
          %span{aria: {hidden: true}}= "X"
          %span.sr-only= "Close"
        %h2= t(:reset_pass)
      .scribeModal--body.resetPassModal--body
        = form_tag reset_password_url, {class: 'scribeForm resetPassForm scribeGrid--newColumn10 js-lowercase-values js-validateForm', remote: true} do
          %h4.u-centralized.u-slimTitle.scribeGrid--row= "Email"
          = text_field_tag :email, params[:email], class: 'scribeForm--input', placeholder: t('activerecord.attributes.user.email'), autocomplete: "off", tabindex: 1
          = submit_tag t(:reset_pass), class: 'button mediumLightBlue u-heavyFont u-blockCenter'