config/routes.rb
## Routes structure:
## => http_methods route_name => controller#action, as: route_name (As define the route as a named route. Check: http://guides.rubyonrails.org/routing.html#naming-routes)
## => http_methods order: GET, POST, PUT, DELETE
## => Indentation: One empty line between method changes. One empty line and one commented line before new controller route/resource definition
Rails.application.routes.draw do

    ## Application controller routes
    root to: "application#landing"

    get "search" => "application#search", as: "search"
    get "/404", :to => "application#four_oh_four"
    get "/contacts/:importer/callback" => "application#contacts_callback"
    get "/descubra" => "application#browse_by", type: "discover",  as: "discover"
    get "/hot" => "application#browse_by", type: "popular", as: "popular"

    post "/shortener/:text" => "application#shorten_url", as: "shortener"

    ## Session controller routes
    get "login" => "session#new", as: "login"
    get "logout" => "session#destroy", as: "logout"
    get "auth/facebook/callback" => "session#facebook_auth", as: "facebook_auth"
    get "auth/twitter/callback" => "session#twitter_auth", as: "twitter_auth"
    get "auth/instagram/callback" => "session#instagram_auth", as: "instagram_auth"

    post "authenticate" => "session#create", as: "authenticate"

    ## Users controller routes
    get "password/reset/:password_reset_token" => "users#reset_password", as: "reset_password_edit"
    get "timeline" => "users#timeline", as: "timeline"
    get "facebook_friends" => "users#facebook_friends", as: "facebook_friends"
    get "follow_all_facebook_friends" => "users#follow_all_facebook_friends", as: "follow_all_facebook_friends"

    post "save_profile_photo" => "users#save_profile_photo", as: "save_profile_photo"
    post "save_cover_photo" => "users#save_cover_photo", as: "save_cover_photo"
    post "reset_password" => "users#reset_password_email", as: "reset_password"
    post "follow_or_unfollow/:id" => "users#follow_or_unfollow", constraints: {id: /.*/}, as: "follow_or_unfollow"
    post "follow_all_email_contacts" => "users#follow_all_email_contacts", as: "follow_all_email_contacts"
    post "invite_friend" => "users#invite_single_contact", as: "invite_friend"
    post "invite_all_contacts" => "users#invite_all_email_contacts", as: "invite_all_contacts"
    post "merge_accounts" => "users#merge_accounts", as: "merge_accounts"
    post "complete_registration" => "users#complete_registration", as: "complete_registration"

    put "update_password" => "users#update_password", as: "update_password"
    put "finish_tour" => "users#finish_tour", as: "finish_tour"

    ## Texts controller routes
    get "load_search_results" => "texts#load_search_results", as: "load_search_results"

    post ":id/create_tag_path" => "texts#create_tag", as: "create_tag"

    delete ":id/delete_tag/:tag_id" => "texts#delete_tag", as: "delete_tag"

    ## Categories controller routes
    get "/load_from/:category" => "categories#load_from", as: "load_from"
    get "c/:locale" => "categories#index", as: "category_with_locale"

    ## Tags controller routes
    get "/tags" => "tags#index", as: "tags"
    get "/load_texts" => "tags#load_texts", as: "load_from_tags"

    ## Categories resources
    resources :categories, param: :locale_key, only: [:index], path: "c" do
        get "last/:locale" => "categories#last_texts_full", as: "last_texts_full"
        get "most/:locale" => "categories#most_viewed_full", as: "most_viewed_full"
    end

    ## Texts resources
    resources :texts, only: [:new, :create, :edit, :update, :show, :destroy], path: "t" do
        get "commentline" => "texts#commentline", as: "commentline"
        
        post "publish" => "texts#publish", as: "publish"
        post "post_comment" => "texts#post_comment", as: "post_comment"
        post "recommendations_details" => "texts#recommendations_details", as: "recommendations_details"
        post "cover_text_photo" => "texts#save_text_cover", as: "insert_cover"
        post "insert_text_image" => "texts#save_text_image", as: "insert_image"
        
        delete "delete_comment" => "texts#delete_comment", as: "delete_comment"
        delete "delete_text_image" => "texts#delete_text_image", as: "delete_image"
    end

    ## Users resources
    resources :users, :param => :id, constraints: {id: /.*/}, only: [:new, :create, :edit, :update], path: "u" do
        get "/profile" => "users#profile", as: "show"
        get "/following" => "users#following", as: "following"
        get "/followers" => "users#followers", as: "followers"
        get "/stats" => "users#see_stats", as: "see_stats"
        get "/link_facebook" => "users#link_facebook_account", as: "link_facebook"

        post "/deactivate_account" => "users#deactivate_account", as: "deactivate_account"

        put "/unlink_facebook" => "users#unlink_facebook", as: "unlink_facebook"
        put "/unlink_twitter" => "users#unlink_twitter", as: "unlink_twitter"
        put "/unlink_instagram" => "users#unlink_instagram", as: "unlink_instagram"

        member do
            post "/recommend/:text_id/" => "users#recommend", as: "recommend"
        end
    end

    devise_for :master_scribers
    authenticate :master_scriber do
      mount RailsAdmin::Engine => '/admin'
    end
end

app/models/category.rb
 class Category < ActiveRecord::Base
 	include Searchable
	validates :name, uniqueness: true, presence: true

	has_many :texts

	def list_texts_by_type(type, language = Language.where(locale: I18n.locale).first,page = 1, per=5)
		@list = self.texts(true).includes(:user, :tags, :language).where(language: language, is_draft: false)
		case type
		when ScribeConstants::TOP_TEN
			top_ten(page, per)
		when ScribeConstants::LAST_TEXTS
			last_texts(page, per)
		when ScribeConstants::MOST_VIEWED
			most_viewed(page, per)
		end
	end

	private

	def last_texts(page, per)
		@list.order("published_at DESC")
			.page(page)
			.per(per)
	end

	def most_viewed(page, per)
		@list.order("unique_views_counter DESC")
			.where("published_at >= ?", 1.week.ago)
			.page(page)
			.per(per)
	end

	def top_ten(page, per)
		@list.order("recommendations_count DESC")
			.where("published_at >= ?", 1.week.ago)
			.page(page)
			.per(per)
	end
end

app/controllers/categories_controller.rb
## Rails generated class, currently unused

class CategoriesController < ApplicationController
  before_action :define_locale
  before_action :set_details, only: [:last_texts_full, :most_viewed_full]

  helper_method :categories_header_attrs

  ## GET /c
  ## Load categories page with it's subdivisions
  def index
    @categories = Category.includes(:texts).all
  end

  ## GET /c/:locale/last_texts/:page
  ## Load last 10 texts

  ## GET /c/:locale/most_viewed/:page
  ## Load 10 most viewed texts
  %w(last_texts most_viewed).each do |type|
    define_method("#{type}_full") do
      @texts = @category.list_texts_by_type(type, @locale, @page, 10)
      respond_to do |format|
        format.html { render "detailed_category", locals: {title: I18n.t(type.to_sym), action: "#{type}_full".to_sym} }
      end
    end
  end

  def load_from
    @texts = Text.where({category_id: params[:category], is_draft: false, language: Language.where(locale: I18n.locale).first})
      .where('recommendations_count > (?)', 9)
      .limit(params[:limit])
      .order("RANDOM()")

    respond_to do |format|
      format.html {render partial: "application/text/blocks", locals: {texts: @texts, container_class: 'landingPage--categoryTexts'}}
    end
  end

  private

    def default_meta
      prev = super
      prev[:title] = "#{t(:categories)} - Scribe"
      prev
    end

    def categories_header_attrs(cat)
      attrs = {
        href: "#", 
        role: "tab",
        data: {
          toggle: "tab",
          target: "##{cat.locale_key}"
        }
      }

      if !params[:action].eql?("index")
        attrs[:href] = categories_path
        attrs[:data][:toggle] = nil
      end

      attrs
    end

    # Use callbacks to share common setup or constraints between actions.
    def define_locale
      @locale = params[:locale].blank? ? Language.where(locale: I18n.locale).first : Language.find(params[:locale])
    end

    def set_details
      @categories = Category.all
      @category = Category.where(locale_key: params[:category_locale_key]).first
      @page = params[:page].blank? ? 1 : params[:page]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :about)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories_header.haml
%section#categories-header
  .sg-container
    %ul#categories-list.nav.nav-tabs{role: "tablist"}
      - @categories.each_with_index do |cat, idx|
        %li.sg-col-3.text-center
          %a{categories_header_attrs(cat)}= t(cat.locale_key.to_sym)
  = render "users/user_header_nav"

app/views/categories/detailed_category.html.haml
= render "categories_header"
%section.scribeGrid--newContainer.categoriesSection
  .scribeGrid--row.section--header
    .scribeGrid--newColumn16
      %h2.u-slimTitle= "#{t(@category.locale_key.to_sym)}: #{title}"
  %div.categoriesContainer
    = render "application/text/blocks", texts: @texts, size: "full"
    = paginate @texts, params: {controller: "categories", action: action}

app/views/categories/index.html.haml
= render "categories_header"
%section.scribeGrid--newContainer.categoriesSection
  .scribeGrid--row.section--header
    .scribeGrid--newColumn6
      %h3.u-lightFont.js-currentCategory
    .scribeGrid--newColumn6
      %ul.languageSwitcher.u-horizontalMenu
        - Language.find_each do |lang|
          %li{class: ("active" if lang == @locale)}
            %a{href: category_with_locale_path(lang.id)}= lang.name
    .scribeGrid--newColumn4
      = form_tag search_url, method: :get, class: 'searchForm' do
        = text_field_tag :query, "#{@query}", placeholder: t(:search), class: 'searchForm--inputField'
  .tab-content
    - @categories.each_with_index do |cat, idx|
      .tab-pane.fade{id: cat.locale_key}
        .scribeGrid--row
          .scribeGrid--newColumn8.scribeGrid--gutterRight1.scribeGrid--newMobileColumn16.scribeGrid--mobile-noGutterRight
            %h1.categoriesSection--title.u-lightFont= t(:last_texts)
            = render "application/text/blocks", texts: cat.list_texts_by_type(ScribeConstants::LAST_TEXTS, @locale), has_gutter: false
            .see-more-container.text-center
              = link_to t(:load_more), category_last_texts_full_path(cat.locale_key, @locale.id), class: 'see-more'
          .scribeGrid--newColumn8.scribeGrid--gutterLeft1.scribeGrid--newMobileColumn16.scribeGrid--mobile-noGutterLeft
            %h1.categoriesSection--title.u-lightFont= t(:most_viewed)
            = render "application/text/blocks", texts: cat.list_texts_by_type(ScribeConstants::MOST_VIEWED, @locale), has_gutter: false
            .see-more-container.text-center
              = link_to t(:load_more), category_most_viewed_full_path(cat.locale_key, @locale.id), class: 'see-more'
        .scribeGrid--row
          .scribeGrid--newColumn16
            %h1.categoriesSection--title.u-lightFont= t(:most_recommended_week)
        = render "application/text/blocks", texts: cat.list_texts_by_type(ScribeConstants::TOP_TEN, @locale, 1, 10), size: "full"