config/routes.rb
## Routes structure:
## => http_methods route_name => controller#action, as: route_name (As define the route as a named route. Check: http://guides.rubyonrails.org/routing.html#naming-routes)
## => http_methods order: GET, POST, PUT, DELETE
## => Indentation: One empty line between method changes. One empty line and one commented line before new controller route/resource definition
Rails.application.routes.draw do

    ## Application controller routes
    root to: "application#landing"

    get "search" => "application#search", as: "search"
    get "/404", :to => "application#four_oh_four"
    get "/contacts/:importer/callback" => "application#contacts_callback"
    get "/descubra" => "application#browse_by", type: "discover",  as: "discover"
    get "/hot" => "application#browse_by", type: "popular", as: "popular"

    post "/shortener/:text" => "application#shorten_url", as: "shortener"

    ## Session controller routes
    get "login" => "session#new", as: "login"
    get "logout" => "session#destroy", as: "logout"
    get "auth/facebook/callback" => "session#facebook_auth", as: "facebook_auth"
    get "auth/twitter/callback" => "session#twitter_auth", as: "twitter_auth"
    get "auth/instagram/callback" => "session#instagram_auth", as: "instagram_auth"

    post "authenticate" => "session#create", as: "authenticate"

    ## Users controller routes
    get "password/reset/:password_reset_token" => "users#reset_password", as: "reset_password_edit"
    get "timeline" => "users#timeline", as: "timeline"
    get "facebook_friends" => "users#facebook_friends", as: "facebook_friends"
    get "follow_all_facebook_friends" => "users#follow_all_facebook_friends", as: "follow_all_facebook_friends"

    post "save_profile_photo" => "users#save_profile_photo", as: "save_profile_photo"
    post "save_cover_photo" => "users#save_cover_photo", as: "save_cover_photo"
    post "reset_password" => "users#reset_password_email", as: "reset_password"
    post "follow_or_unfollow/:id" => "users#follow_or_unfollow", constraints: {id: /.*/}, as: "follow_or_unfollow"
    post "follow_all_email_contacts" => "users#follow_all_email_contacts", as: "follow_all_email_contacts"
    post "invite_friend" => "users#invite_single_contact", as: "invite_friend"
    post "invite_all_contacts" => "users#invite_all_email_contacts", as: "invite_all_contacts"
    post "merge_accounts" => "users#merge_accounts", as: "merge_accounts"
    post "complete_registration" => "users#complete_registration", as: "complete_registration"

    put "update_password" => "users#update_password", as: "update_password"
    put "finish_tour" => "users#finish_tour", as: "finish_tour"

    ## Texts controller routes
    get "load_search_results" => "texts#load_search_results", as: "load_search_results"

    post ":id/create_tag_path" => "texts#create_tag", as: "create_tag"

    delete ":id/delete_tag/:tag_id" => "texts#delete_tag", as: "delete_tag"

    ## Categories controller routes
    get "/load_from/:category" => "categories#load_from", as: "load_from"
    get "c/:locale" => "categories#index", as: "category_with_locale"

    ## Tags controller routes
    get "/tags" => "tags#index", as: "tags"
    get "/load_texts" => "tags#load_texts", as: "load_from_tags"

    ## Categories resources
    resources :categories, param: :locale_key, only: [:index], path: "c" do
        get "last/:locale" => "categories#last_texts_full", as: "last_texts_full"
        get "most/:locale" => "categories#most_viewed_full", as: "most_viewed_full"
    end

    ## Texts resources
    resources :texts, only: [:new, :create, :edit, :update, :show, :destroy], path: "t" do
        get "commentline" => "texts#commentline", as: "commentline"
        
        post "publish" => "texts#publish", as: "publish"
        post "post_comment" => "texts#post_comment", as: "post_comment"
        post "recommendations_details" => "texts#recommendations_details", as: "recommendations_details"
        post "cover_text_photo" => "texts#save_text_cover", as: "insert_cover"
        post "insert_text_image" => "texts#save_text_image", as: "insert_image"
        
        delete "delete_comment" => "texts#delete_comment", as: "delete_comment"
        delete "delete_text_image" => "texts#delete_text_image", as: "delete_image"
    end

    ## Users resources
    resources :users, :param => :id, constraints: {id: /.*/}, only: [:new, :create, :edit, :update], path: "u" do
        get "/profile" => "users#profile", as: "show"
        get "/following" => "users#following", as: "following"
        get "/followers" => "users#followers", as: "followers"
        get "/stats" => "users#see_stats", as: "see_stats"
        get "/link_facebook" => "users#link_facebook_account", as: "link_facebook"

        post "/deactivate_account" => "users#deactivate_account", as: "deactivate_account"

        put "/unlink_facebook" => "users#unlink_facebook", as: "unlink_facebook"
        put "/unlink_twitter" => "users#unlink_twitter", as: "unlink_twitter"
        put "/unlink_instagram" => "users#unlink_instagram", as: "unlink_instagram"

        member do
            post "/recommend/:text_id/" => "users#recommend", as: "recommend"
        end
    end

    devise_for :master_scribers
    authenticate :master_scriber do
      mount RailsAdmin::Engine => '/admin'
    end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  before_action :set_text, only: [:show, :edit, :update, :destroy, :create_tag,
      :delete_tag, :save_text_cover, :save_text_image, :delete_text_image]
  before_action :check_credentials, only: [:edit, :update, :destroy, :new]
  before_action :check_ownership, only: [:edit, :destroy]
  before_action only: [:new, :edit] do
    render_footer(false)
    render_header(false)
  end
  before_action only: [:index, :show] do
    render_header(true)
    render_footer(false)
  end

  helper_method :text_style


  ## GET /t
  ## Unused rails generated method
  ## TODO: Define usage
  def index
    @texts = Text.all
  end

  ## GET /t/new/[id]
  ## Params: [id]
  ## Success: render new text page
  ## Error: 
  ## TODO: Error handling
  ## TODO: Find smarter way to create or retrieve drafts to avoid Database garbage (Using id as a parameter)
  ## Rails generated method
  def new
    @text = @current_user.texts.create

    respond_to do |format|
      format.html { redirect_to edit_text_url(@text) }
    end
  end

  # GET /t/id/edit
  def edit
  end

  ## GET /t/id
  ## Params: id
  ## Success:
  ##    - If user is logged and is the text owner, render it!
  ##    - If user is logged and isn't the text owner/If user isn't logged in:
  ##        - If text is draft, redirect_to user profile
  ##        - If text isn't draft, render it!
  ## Error: 
  ## TODO: Error handling
  ## TODO: Rewrite success flow
  ## Rails generated method
  def show
    if @text.is_draft && @text.user != @current_user
      redirect_to root_url
    else
      impressionist(@text) unless @text.is_draft 
      logger.debug "Impressions: #{@text.impressionist_count(filter: :ip_address)}"
      @suggestions = Text.generate_suggestions(2, @text.id)
      respond_to do |format|
        format.html {render layout: !request.xhr?}
      end
    end
  end

  ## PUT /t/id
  ## Params: id, title, sub_title, description, category_id, language_id
  ## Success: redirect_to text page
  ## Error: Render models errors
  ## TODO: Error handling
  ## Rails generated method
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.json { render json: {saved: true, redirect_to: text_url(@text), publish: text_publish_url(@text),tags_url: url_for(create_tag_path(@text))}, status: :ok, location: @text }
      else
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  ## DELETE /t/id
  ## Params: id
  ## Success: redirect_to user profile
  ## Error: 
  ## TODO: Error handling
  ## TODO: Rewrite code structure so text doesn't get ACTUALLY deleted from database
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to user_show_path(@current_user)} unless request.xhr?
      format.json { render json: {redirect_to: user_show_url(@current_user)}, status: :ok}
    end
  end

  ## POST /cover_text_photo
  ## Params: text_cover
  ## Success: Return text_cover url
  ## Error: Renders model errors
  ## TODO: Error handling
  def save_text_cover
    unless @text.cover.nil?
      @text.text_images.find(@text.cover.id).destroy
    end
    @text.text_images.create({deferred_photo: params[:text][:text_cover], is_cover: true})
    respond_to do |format|
      if @text.save
        format.json {render json: @text.cover.photo.url, status: :ok}
      else
        format.json {render json: @text.errors, status: :unprocessable_entity}
      end
    end
  end

  ## POST /text_image
  ## Params: text_image
  ## Success: Return text_image url
  ## Error: Renders model errors
  ## TODO: Error handling
  def save_text_image
    @text.text_images.create({deferred_photo: params[:text][:text_image], is_cover: false})

    respond_to do |format|
      if @text.save
        format.json {render json: {url: @text.text_images.last.photo.url(:full_show), id: @text.text_images.last.id}, status: :ok}
      else
        format.json {render json: @text.errors, status: :unprocessable_entity}
      end
    end
  end

  ## DELETE /text_image
  ## Params: image_id
  ## Success: Delete text image
  ## Error: Renders model errors
  ## TODO: Error handling
  def delete_text_image
    @img = @text.text_images.find(params[:image_id])

    respond_to do |format|
      if @img.destroy!
        format.json {render json: {destroyed: true}, status: :ok}
      else
        format.json {render json: @text.errors, status: :unprocessable_entity}
      end
    end
  end

  ## POST /t/id/publish
  ## Params: id
  ## Success: Change text from draft status and redirect to text show
  ## Error: Renders model errors
  ## TODO: Error handling
  ## TODO: Review slug generation in the proccess
  def publish
    @text = Text.friendly.find(params[:text][:id])
    @text.slug = nil

    respond_to do |format|
      if @text.update(text_params) && @text.publish
        format.json {render json: {redirect_url: text_url(@text)}, status: :ok, location: @text}
      else
        format.json {render json: @text.errors, status: :unprocessable_entity}
      end
    end
  end

  ## POST /id/create_tag
  ## Params: id, name
  ## Success: Create or retrieve tag for text
  ## Error: Returns uniqueness/limits error message
  def create_tag
    respond_to do |format|
      @tag = @text.insert_tag(tags_params)
      if @tag
        format.json {render json: {obj: @tag, url: delete_tag_url(@text,@tag), confirm: I18n.t(:exclusion_confirm)} , status: :ok}
      else
        format.json {render json: t(:tags_num_reached) , status: :unprocessable_entity}
      end
    end
  end

  ## GET /t/id/commentline
  ## Params: id
  ## Success: Retrieve text commentline and current user
  def commentline
    text = Text.friendly.find(params[:text_id])
    redirect_to text_url(text) unless request.xhr?
    if request.xhr?
      @commentline = {
        current_user: nil,
        comments: []
      }

      if @current_user
        @commentline[:current_user] = {
          id: @current_user.id,
          name: @current_user.name,
          avatarUrl: @current_user.profile_photo.url(:thumbs),
          authorUrl: user_show_url(@current_user)
        }
      end

      if text.comment_count > 0
        text.commentline(limit: 999).group_by{
          |c|
          c.section_id
        }.each {
          |s_id, comments|

          @commentline[:comments] << {
            sectionId: s_id.to_s,
            comments: []
          }

          comments.sort_by{
            |c|
            c.id
          }.each {
            |comment|
            json_comment = {
              authorAvatarUrl: comment.user.profile_photo.url(:thumbs),
              authorName: comment.user.name,
              comment: comment.body,
              authorId: comment.user.id,
              id: comment.id,
              authorUrl: user_show_url(comment.user)
            }

            if comment.parent_id.blank?
              json_comment[:comment] = '' if comment.deleted
              json_comment[:replies] = []
              json_comment[:deleted] = comment.deleted
              
              @commentline[:comments].last[:comments] << json_comment
            else
              json_comment[:parentId] = comment.parent_id
              parent = @commentline[:comments].last[:comments].find {
                |c|
                c[:id] == comment.parent_id
              }
              parent[:replies] << json_comment
            end
          }
        }
      end

      respond_to do |format|
        format.json {render json: @commentline, success: :ok}
      end
    end
  end

  ## POST /t/id/post_comment
  ## Params: id, section, comment, parent
  ## Success: Add comment to commentline
  def post_comment
    text = Text.friendly.find(params[:text_id])
    
    comment = {
      commentable: text,
      body: params[:comment],
      section_id: params[:section],
      parent_id: params[:parent]
    }

    @comment = @current_user.post_comment(comment)
    respond_to do |format|
      format.json {render json: @comment.to_json, status: :ok}
    end
  end

  ## DELETE /t/id/delete_comment
  ## Params: id, section, comment
  ## Success: Add comment to commentline
  def delete_comment
    @comment = @current_user.comments.where(id: params[:comment]).first
    @comment_id = @comment.id
    @section_id = @comment.section_id
    @parent_id = @comment.parent_id
    
    text = @comment.commentable

    is_parent = text.comments.where(parent_id: @comment_id)

    if is_parent.blank?
      @comment.destroy
    else
      @comment.update({
        deleted: true
      })
    end
    respond_to do |format|
      format.json {render json: {comment_id: @comment_id, section_id: @section_id, parent_id: @parent_id}, status: :ok}
    end
  end

  ## DELETE /id/delete_tag/tag_id
  ## Params: id, tag_id
  ## Success: Delete tag from text
  ## Error: 
  ## TODO: Error handling
  def delete_tag
    respond_to do |format|
      format.json {render json: @text.tags.delete(params[:tag_id])}
    end
  end

  ## POST /id/recommendations_details
  ## Params: id
  ## Success: Returns list of users who recommended the text
  def recommendations_details
    @text = Text.friendly.find(params[:text_id])

    respond_to do |format|
      format.html { render partial: "users/user_list", locals: {users: @text.recommenders}, status: :ok }
    end
  end

  private

  ## Callback helpers
  def set_text
    param = params[:id] || params[:text_id]
    @text ||= Text.friendly.find(param)
  end

  ## Meta tags helpers
  def facebook_meta
    prev = super
    if !@text.nil?
      prev[:og][:type] = "article"
      prev[:og][:title] = @text.title
      prev[:og][:url] = url_for(@text)
      prev[:og][:image].unshift(@text.user.profile_photo.url) unless @text.user.profile_photo.blank?
      prev[:og][:image].unshift(@text.cover.photo.url) unless @text.cover.blank?

app/helpers/texts_helper.rb
module TextsHelper

	def sanitized_content_for(tag,tag_for,content)
		attrs = {class: 'scribeGrid--column10 textHeader--title'}
		if content.blank?
			content = ''
			attrs[:class] << ' placeholdify'
			if tag_for.eql?(:sub_title)
				return nil
			else
				attrs[:data] = {placeholder: t(tag_for)}
			end
		end
		content_tag(tag, content, attrs)
	end
end

app/views/texts/_about_author.html.haml
.textFooter--authorDetails
  %hr.u-sectionStrike--aboutAuthor.u--mobile-xsHidden
  .userInfo.u-clearfix.u-isStriked
    %em.userInfo--writtenBy= t(:written_by)
    .userInfo--dateSection
      %h2.date--day= text.published_at.blank? ? text.updated_at.strftime('%d') : text.published_at.strftime('%d')
      %h6.date--month= text.published_at.blank? ? I18n.l(text.updated_at, format: :short_month).upcase : I18n.l(text.published_at, format: :short_month).upcase
      %h6.date--year= text.published_at.blank? ? text.updated_at.strftime('%Y') : text.published_at.strftime('%Y')
    .userInfo--pictureSection
      %img.userInfo--profileThumb{src: text.user.profile_photo.url(:thumbs), alt: text.user.name}
    .userInfo--descriptionSection
      = link_to text.user.name, user_show_url(text.user), class: 'userInfo--userName', title: text.user.name
      = link_to "#{t("activerecord.attributes.user.texts", count: text.user.published_texts.count)}", user_show_url(text.user), class: 'userInfo--textsCount'
    .userInfo--socialSection
      = follow_unfollow_button(text.user)

app/views/texts/_bookshelf_board.html.haml
.textFooter--bookshelfBoard
  %hr.u-sectionStrike--thirdWidth.u--mobile-xsHidden
  %ul#bookshelf-board.u-horizontalMenu.u-clearfix.u-isStriked
    %li#recommendation.socialBtn.socialBtn--recommend.readerIcons{class: (' isRecommended' if @current_user && @current_user.recommended?(@text))}
      %span.recommendation--count.js-recommendation-count= @text.recommendations_count
      = link_to t(:recommend, count: @current_user ? (@current_user.recommended?(@text) ? 1 : 0) : 0), recommend_url , remote: true, method: :post, class: ["js-recommend", ("sup-trigger" if @current_user.blank?)], data: {cout_title: t(:rec_now_title), cout_content: t(:rec_now_content)}

app/views/texts/_direct_upload.html.haml
= s3_uploader_form callback_url: callback, class: 's3_uploader_text', callback_param: "text[#{param}]", id: id, expiration: 24.hours.from_now.utc.iso8601, max_file_size: 50.megabytes do
  = file_field_tag :file, accept: 'image/png,image/gif,image/jpeg'

app/views/texts/_form.haml
= render "scribe_modal", modal_title: "Oops!", modal_subtitle: t(:not_ready_to_publish), modal_btn_classes: "btn btn-scribe full-width-btn btn-scribe-lb"
%section#text-editor-container
  %article#new-text 
    %section#text-header.editor{class: (@text.cover.blank? ? " no-cover" : " has-cover"), style: text_style(@text, true), data: {gradient: image_url('gradiente_branco_reverse.png')}}
      .gradient-overlay{style: "background: url(#{image_url('gradiente_branco_reverse.png')}) center center repeat-x transparent; background-size: contain"}
      %figure#cover-photo
        = image_tag @text.cover.nil? ? '' : @text.cover.photo.url
      .sg-container.textContainer
        .sg-row.text-header-content
          .sidebar-area
            = render 'form_header_sidebar', text: @text
          .main-area
            %h1#title.placeholdify.editable.sg-col-10{tabindex: 1,contenteditable: true, data: {placeholder: t(:title), empty: t(:empty_title)}}= @text.title
            %h2#subtitle.placeholdify.editable.sg-col-10{tabindex: 2,contenteditable: true, data: {placeholder: t(:sub_title)}}= @text.subtitle
            #new-text-pic-req.panel.panel--info= t(:upload_picture_text_requirements_html)
            #upload-error.panel.panel--error= t(:upload_error)
    %section#text-body.textContainer
      %input#text-messages{type: "hidden", data: {placeholder: t(:new_text), caption: t(:optional_caption), update_success: t(:updated_text), update_error: t(:update_error), empty_tag: t(:empty_tag), unique_tag: t(:tags_num_reached), delete_image: t(:confirm_delete_image), processing_image: t(:processing_image)}}/
      = form_for @text, html: {id: "new-text-form"} do |form|
        = cktext_area :text, :description, class: 'ckeditor', id: "ck_editor_ta", tabindex: 3, placeholder: t(:new_text), ckeditor: {language: I18n.locale}, data: {delete_text: t(:confirm_delete_text), publish_url: text_publish_url(@text), empty_language: t(:empty_language), empty_category: t(:empty_category), empty_title: t(:empty_title), empty_description: t(:empty_description), delete_image: text_delete_image_url(@text), text_id: @text.slug, has_image: @text.text_images.where(is_cover: false).length > 0, draft_mode: @text.is_draft}
= render 'direct_upload', callback: text_insert_image_url(@text), param: 'text_image', id: 'insert_image'

app/views/texts/_form_header_sidebar.haml
%ul.text-actions
  %li.picture-icon
    = render 'direct_upload', callback: text_insert_cover_url(@text), param: 'text_cover', id: 'text_image'
  %li.category{data: {toggle: "expand-container"}}
    %span.description{data: {default: t(:categories)}}
      = @text.category ? t(@text.category.locale_key.to_sym)[0,3].upcase : t(:categories)
    %ul#text-category.horizontal-list.extensible-container{role: "menu", data: {empty: t(:empty_category)}}
      - Category.find_each do |cat|
        %li{role: "presentation"}
          %a{href: "#", role: "menuitem", data: {value: cat.id, selected: (true if cat.eql?(@text.category) )}}= t(cat.locale_key.to_sym)
    %span.close-btn= "X"
  %li.language{data: {toggle: "expand-container"}}
    %span.description
      = @text.language ? @text.language.name[0,3].upcase : t(:language)
    %ul#text-language.horizontal-list.extensible-container{role: "menu", data: {empty: t(:empty_language)}}
      - Language.find_each do |lang|
        %li{role: "presentation"}
          %a{href: "#", role: "menuitem", data: {value: lang.id, selected: (true if lang.eql?(@text.language))}}= lang.name
    %span.close-btn= "X"
  %li.tags
    %span#left.glyphicon.glyphicon-chevron-left{data: {target: 0}}
    %span#right.glyphicon.glyphicon-chevron-right{data: {target: 0}}
    = form_for :tag, url: url_for(create_tag_path(@text)) , html: {id: "tags-form", class: 'tags-form', data: { :"unique-tag" => t(:tags_num_reached), empty: t(:empty_tag) } }, remote: true,method: "POST" do |f|
      .tags-container
        %span#tags
          - unless @text.tags.blank?
            - @text.tags.each do |tag|
              %span.tag
                %span= tag.name
                %span.delete-tag{data: {confirm: t(:exclusion_confirm), delete: {url: delete_tag_url(@text,tag)}}}= 'x'
        = f.text_field :name, value: '' ,class: "tags-input form-control",id: 'tag-name', placeholder: t(:tag)

app/views/texts/_text_footer.html.haml
%section.textContainer.textFooter
  = render "bookshelf_board", recommended: (@current_user && @current_user.recommended?(@text)) ,recommend_url: (@current_user ? recommend_user_url(@current_user, @text) : '#') unless @text.is_draft
  = render "texts/text_share_board", text: @text unless @text.is_draft
  = render "about_author", text: @text

app/views/texts/_text_header.html.haml
%section.textHeader{class: (@text.cover.blank? ? " noCover" : " hasCover"), style: text_style(@text)}
  .textContainer.scribeGrid--row
    = sanitized_content_for(:h1,:title,@text.title)
    = sanitized_content_for(:h2,:sub_title,@text.subtitle)
    %small.visible-xs-block.scribeGrid--column10.textHeader--mobile-aboutAuthor= "#{t(:written_by)} #{@text.user.name}"
  #header-cover.text-cover

app/views/texts/_text_share_board.haml
.textFooter--shareBoard
  %h3.u-slimTitle.u-centralized= t(:share_on)
  %ul#share-board.u-horizontalMenu.clearfix
    %li.socialBtn.socialBtn--facebook.readerIcons
      %a{href: "#", class: 'facebook-share', data: {href: text_url(text)}}= "Facebook"
    %li.socialBtn.socialBtn--twitter.readerIcons
      %a{href: "#", class: 'js-twitterShare', data: {text: "'#{URI.escape(text.title)} - #{t(:by)} #{text.user.twitter_user ? '@'<<text.user.twitter_user : text.user.name}'", via: "wescribeapp", shortener: shortener_url(text.id)}}= "Twitter"
    %li.socialBtn.socialBtn--gPlus.readerIcons
      %a{href: "#", class: 'js-gPlusShare', data: {url: text_url(text)}}= "Google +"

app/views/texts/_text_sidebar.html.haml
%ul.textSidebar.isInsideText.hidden-xs
  %li.textSidebar--userThumb{style: "background: url(#{@text.user.profile_photo.url(:thumbs)}) center center no-repeat transparent; background-size: cover;"}
    = link_to "", user_show_path(@text.user), data: {toggle: "tooltip", placement: "right", title: @text.user.name}
  %li.textSidebar--datesContainer.u-centralized
    %h2.date--day= @text.published_at.blank? ? @text.updated_at.strftime('%d') : @text.published_at.strftime('%d')
    %h4.date--month= @text.published_at.blank? ? I18n.l(@text.updated_at, format: :short_month).upcase : I18n.l(@text.published_at, format: :short_month).upcase
    %h5.date--year= @text.published_at.blank? ? @text.updated_at.strftime('%Y') : @text.published_at.strftime('%Y')
  - unless @text.category.blank?
    %li.textSidebar--category.u-centralized{data: {toggle: "tooltip", placement: "right", title: t(@text.category.locale_key.to_sym)}}
      %span.u-lightFont= t(@text.category.locale_key.to_sym)[0,3].capitalize<<'.'
  - unless @text.language.blank?
    %li.textSidebar--language.u-centralized{data: {toggle: "tooltip", placement: "right", title: @text.language.name}}
      %span.u-lightFont= @text.language.name[0,3].capitalize<<'.'
  %li.textSidebar--tags.js-expandContainer
    - unless @text.tags.blank?
      %ul.extensibleContainer.u-horizontalMenu.u-clearfix
        - @text.tags.each do |tag|
          %li.tag.light-tag= tag.name
  %li.textSidebar--share
    %a{href: '#share-board'}
  - if @current_user && @text.user == @current_user
    %li.icon--edit 
      = link_to '', edit_text_path(@text)
    %li.icon--delete 
      = link_to '', @text, method: :delete, data: {confirm: t(:exclusion_confirm)}

app/views/texts/edit.html.haml
= render "form"

app/views/texts/new.html.haml
= render "form"

app/views/texts/show.html.haml
%section#text-container
  %article.text
    = render "text_header"
    %section#text-body.textContainer
      #text{data: {commentline: {load: text_commentline_url(@text), post: text_post_comment_url(@text), delete: text_delete_comment_url(@text)}}}
        = @text.description.html_safe
      = render "text_sidebar"
    = render "text_footer"
    - unless @text.is_draft
      %section.suggestionsSection.scribeGrid--row
        .scribeGrid--newContainer
          %h1.suggestionsSection--title.u-lightFont= t(:text_suggestions)
          = render "application/text/blocks", texts: @suggestions, size: "half" unless @text.is_draft
= hidden_field_tag 'my_text', @text.id
= render "register_modal" unless @current_user